export const cards = [
  {
    id: 1,
    title: 'Avert Diplomatic Crisis',
    currentStage: 0,
    actions: [],
    stages: [],
  },
  {
    id: 2,
    title: 'Deliver Emergency Medical Supplies',
    currentStage: 0,
    actions: [],
    stages: [],
  },
  {
    id: 3,
    title: 'Investigate Deep Space Distress Beacon',
    currentStage: 0,
    actions: [],
    stages: [],
  },
  {
    id: 4,
    title: 'Investigate Deep Space Distress Beacon',
    currentStage: 0,
    actions: [],
    stages: [],
  },
  {
    id: 5,
    title: 'Investigate Deep Space Distress Beacon',
    currentStage: 0,
    actions: [],
    stages: [],
  },
  {
    id: 6,
    title: 'Investigate Deep Space Distress Beacon',
    currentStage: 0,
    actions: [],
    stages: [],
  },
  {
    id: 7,
    title: 'Investigate Deep Space Distress Beacon',
    currentStage: 0,
    actions: [],
    stages: [],
  },
  {
    id: 8,
    title: 'Investigate Deep Space Distress Beacon',
    currentStage: 0,
    actions: [],
    stages: [],
  },
  {
    id: 9,
    title: 'Investigate Deep Space Distress Beacon',
    currentStage: 0,
    actions: [],
    stages: [],
  },
  {
    id: 10,
    title: 'Investigate Deep Space Distress Beacon',
    currentStage: 0,
    actions: [],
    stages: [],
  },
];
